hello: py
	echo "Hello, World!"

py: basic.py
	python3 -m basic py

# some_file: other_file
# 	echo "This will always run, and runs second"
# 	touch some_file

# other_file:
# 	echo "This will always run, and runs first"